import { Oswald, Roboto } from "next/font/google";
import "./globals.css";
// Components
import Header from "@/components/Header.jsx";
import Footer from "@/components/Footer.jsx";
import { Toaster } from "react-hot-toast";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ['200', '300', '400', '500', '600', '700'],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-gray-200">
      <body
        className={`${oswald.variable} ${roboto.variable} w-full max-w-[1920px] mx-auto bg-white`}
      >
        <Toaster position="top-center" />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
